# Generated by Django 2.1.4 on 2019-07-06 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cont_address', models.CharField(max_length=100)),
                ('cont_no', models.CharField(max_length=12)),
                ('cont_email', models.EmailField(blank=True, max_length=70)),
                ('cont_locaton', models.CharField(max_length=100)),
                ('cont_map_url', models.CharField(max_length=500)),
            ],
        ),
    ]
