# Generated by Django 2.1.4 on 2019-07-06 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0002_contactdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='socialIcon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_name', models.CharField(max_length=100)),
                ('socail_url', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='contactdetails',
            name='cont_map_url',
            field=models.CharField(max_length=1000),
        ),
    ]
